version: "3"

services:
  app:
    container_name: "${PROJECT_NAME}_app"
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - ${PROJECT_PORT}:80
    volumes:
      - ../:/var/www:cached
