services:
  glitcherbot.crawler:
    class: \ScraperBot\Crawler
    arguments: ['@glitcherbot.storage', '@glitcherbot.event_dispatcher']

  glitcherbot.storage:
    alias: glitcherbot.storage.sqlite3

  glitcherbot.storage.sqlite3:
    class: \ScraperBot\Storage\SqlLite3Storage

  glitcherbot.event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  glitcherbot.renderer:
    class: ScraperBot\Renderer\TwigRenderer

  glitcherbot.route_manager:
    class: ScraperBot\Routing\RouteManager

  glitcherbot.controller_resolver:
    class: Symfony\Component\HttpKernel\Controller\ControllerResolver

  glitcherbot.argument_resolver:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver

  glitcherbot.csv_manager:
    class: ScraperBot\CsvManager
